# Generated by Django 4.0.5 on 2022-07-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filhoa',
            options={'verbose_name_plural': 'filhos A'},
        ),
        migrations.AlterModelOptions(
            name='filhob',
            options={'verbose_name_plural': 'filhos B'},
        ),
        migrations.AlterField(
            model_name='filhoa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filhob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pai',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
